# This file was generated by wxPython's wscript.

VERSION_STRING    = '4.0.2'
MAJOR_VERSION     = 4
MINOR_VERSION     = 0
RELEASE_NUMBER    = 2
BUILD_TYPE        = 'release'

VERSION = (MAJOR_VERSION, MINOR_VERSION, RELEASE_NUMBER, '')
